version: 2.1

master-only: &master-only
  filters:
    branches:
      only: master

executors:
  builder:
    docker:
      - image: duckpodger/python3-node-aws-terraform

jobs:
  setup:
    executor: builder
    steps:
      - restore_cache:
          keys:
            - git-v1-{{ .Branch }}-
            - git-v1-

      - checkout

      - restore_cache:
          keys:
            - python-v1-{{ .Branch }}-
            - python-v1-

      - run:
          name: install virtual env
          command: |
            export PIPENV_VENV_IN_PROJECT=true
            pipenv install --dev --deploy
            if [ ! -d "test-reports" ]; then
              mkdir test-reports
            fi

      - run:
          name: terraform
          command: |
            . .circleci/env.sh
            cd infrastructure
            terraform init
            terraform get --update
            terraform workspace new $SSM_SOURCE_STAGE || terraform workspace select $SSM_SOURCE_STAGE
            echo checking formatting
            terraform fmt -check=true
            echo making the plan
            terraform plan -var ssm_source_stage=$SSM_SOURCE_STAGE -var account_id=$ACCOUNT_ID -no-color -out=plan.file > terraform.plan

      - persist_to_workspace:
          root: .
          paths:
            - "*"

      - store_artifacts:
          path: .generated

      - store_artifacts:
          path: infrastructure/plan.file

      - store_artifacts:
          path: infrastructure/terraform.plan

      - persist_to_workspace:
          root: .
          paths:
            - "*"

      - save_cache:
          key: git-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - save_cache:
          key: python-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".venv"
            - ".generated"
            - ".pytest_cache"

  unit-test:
    executor: builder
    steps:
      - attach_workspace:
          at: .
      - run:
          name: integration tests
          command: |
            . .circleci/env.sh
            pytest --junitxml=test-reports/junit.xml -m unit tests
      - store_test_results:
          path: test-reports

  deploy:
    executor: builder
    steps:
      - attach_workspace:
          at: .
      # TODO change this when we move on to having multiple environments
      - run:
          name: deploy
          command: |
            . .circleci/env.sh
            cd infrastructure
            terraform workspace new dev || terraform workspace select dev
            terraform apply plan.file

workflows:
  version: 2
  terraform-infrastructure:
    jobs:
      - setup
      - unit-test:
          requires: [ setup ]
      - approve:
          type: approval
          requires:
            - unit-test
          <<: *master-only
      - deploy:
          requires: [ approve ]
          <<: *master-only




